### ISSUE TITLE
Simplify setting target temperatures

### ISSUE THREAD

**Issue by mkaiser** [roberreiter/StiebelEltron-heatpump-over-esphome-can-bus#1]
Hi, 

I am using this integration now for a week and I am really happy to get things working without the official ISG from Stiebel Eltron :)

Starting to automize, I made some sliders to set the water target temperatures:

![image](https://user-images.githubusercontent.com/29856783/224280414-e45b7c9c-a896-43f5-ae11-6a291f497cbb.png)

that are just a few lines in yaml: 

```
# getting input sliders for temperatures
input_number:
  set_hp_water_comfort_target_temp:
    name: Set water comfort target temp
    min: 40
    max: 60
    step: 1

  set_hp_water_eco_target_temp:
    name: Set water eco target temp
    min: 40
    max: 60
    step: 1
```
To transfer newly set target temperatures I like to use the predefined "esphome.heatpump_pull_canmsg"
(I just named my ESP device "heatpump")

yaml-code:
```
automation:
  - id: "automation_heatpump_set_comfort_water_target_temp"
    alias: "heatpump set comfort water target temperature"
    trigger:
      - platform: state
        entity_id:
          - input_number.set_hp_water_comfort_target_temp
    condition: []
    action:
      - service: esphome.heatpump_pull_canmsg
        data:
          idx: TODO
          addr: TODO
          val: "{{ states('input_number.set_hp_water_comfort_target_temp') | int *10}}"

  - id: "automation_heatpump_set_eco_water_target_temp"
    alias: "heatpump set eco water target temperature"
    trigger:
      - platform: state
        entity_id:
          - input_number.set_hp_water_eco_target_temp
    condition: []
    action:
      - service: esphome.heatpump_pull_canmsg
        data:
          idx: TODO
          addr: TODO
          val: "{{ states('input_number.set_hp_water_eco_target_temp') | int *10}}"

```

... but I am not sure what to set for "idx" and "addr". Could you help me with that?

I have the same heatpump as you do, but with the "Tecalor" label : Tecalor TTC 07 cool
